  version: '3.8'

  services:
    backend:
      build: ./backend
      environment:
        - PORT=5000
      expose:
        - "5000"

    frontend:
      build: ./frontend
      environment:
        - PORT=3000
        - BACKEND_URL=/api
      expose:
        - "3000"
      depends_on:
        - backend

    nginx:
      build: ./nginx
      ports:
        - "9091:80"
      depends_on:
        - backend
        - frontend